### ISSUE TITLE
Stuck at 'setup'

### ISSUE THREAD

**Issue by MAnoDew** [Luc1412/EasyMaintenance#2]
Hi there,

When I join my server, I want to say hi to everyone.
But a message appears:
[EasyMaintenance-Setup] Error! Your Input is not valid! Try Again!
I can't do anything while I'm at the setup.
I would appreciate some help :)

~MAnoDew

**Comment by Luc1412** [comment]
You must choose your config language first ("de" "en")

**Comment by MAnoDew** [comment]
Thanks! ^^
